# permissions for end users to view stardeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stardeployment-viewer-role
rules:
- apiGroups:
  - starrocks.com
  resources:
  - stardeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - starrocks.com
  resources:
  - stardeployments/status
  verbs:
  - get
