# permissions for end users to edit stardeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stardeployment-editor-role
rules:
- apiGroups:
  - starrocks.com
  resources:
  - stardeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - starrocks.com
  resources:
  - stardeployments/status
  verbs:
  - get
